sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose run lint

before_install:
  - openssl aes-256-cbc -K $encrypted_67ed219c14e0_key -iv $encrypted_67ed219c14e0_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
  - chmod 600 ~/.ssh/id_rsa
  - ./deploy.sh

notifications:
  email:
    - me@kliy.es