FROM python:3.7-alpine

COPY pylint.conf /opt

COPY requirements.txt /opt
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
 apk add build-base && \
 pip install -i https://pypi.doubanio.com/simple -r /opt/requirements.txt pylint