version: '3.7'

services:

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    volumes:
      - ./game_store:/opt/src
    working_dir: /opt/src
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    command: ${COMMAND}

  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
    hostname: lint
    volumes:
      - ./game_store:/opt/src
      - ./reports/lint:/opt/reports
    working_dir: /opt/src
    command: sh -c "pylint --exit-zero --rcfile=/opt/pylint.conf /opt/src | tee /opt/reports/results.txt"